site_name: AgoraCare Documentation
site_description: Documentación técnica de AgoraCare
site_author: Adrian
site_url: https://tu-usuario.github.io/sphinxDocs

theme:
  name: readthedocs
  locale: es

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - codehilite

