site_name: AgoraCare Documentation
site_description: Documentación técnica de AgoraCare
site_author: Adrian

theme:
  name: readthedocs
  locale: es
  favicon: img/favicon.svg

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - codehilite

